[build-system]
requires = ["scikit-build-core>=0.5", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "papercube"
version = "1.0.1"
description = "A mathematically consistent N×N×N Rubik's Cube simulation library."
readme = "README.md"
authors = [
    { name = "Ayush", email = "ayush.soni30705@gmail.com" }
]
requires-python = ">=3.8"
dependencies = []

[project.urls]
Homepage = "https://github.com/ayush00soni/PaperCube"

[tool.scikit-build]
# Tell scikit-build where your main CMakeLists.txt is
cmake.source-dir = "." 

# Force CMake to use the 64-bit architecture generator
cmake.args = ["-A", "x64"]